ifndef QCONFIG
QCONFIG=qconfig.mk
endif
include $(QCONFIG)

define PINFO
PINFO DESCRIPTION=ota update demo application
endef

INSTALLDIR=$(firstword $(INSTALLDIR_$(OS)) usr/bin)

NAME = ota_test

CCFLAGS= -DRUN_IN_QNX -D_FILE_OFFSET_BITS=64

EXTRA_INCVPATH += $(PRODUCT_ROOT)/lib/include/
EXTRA_LIBVPATH += $(PRODUCT_ROOT)/lib/nto/aarch64/so.le/

#####AUTO-GENERATED by packaging script... do not checkin#####
   INSTALL_ROOT_nto = $(PROJECT_ROOT)/../../../../install
   USE_INSTALL_ROOT=1
##############################################################

include $(MKFILES_ROOT)/qmacros.mk

include $(MKFILES_ROOT)/qtargets.mk

LIBS += slots_parse
LIBS += sdrvproperty