ifndef QCONFIG
QCONFIG=qconfig.mk
endif
include $(QCONFIG)

define PINFO
PINFO DESCRIPTION=ota update library
endef

INSTALLDIR=$(firstword $(INSTALLDIR_$(OS)) usr/lib)

NAME = slots_parse

EXTRA_INCVPATH += $(PROJECT_ROOT)/include/

CCFLAGS= -DRUN_IN_QNX -D_FILE_OFFSET_BITS=64 -DSUPPORT_PROPERTY_LIB=0

LIBS += slog2
LIBS += rpmsgS
LIBS += rpmsg-utilS
LIBS += socket
LIBS += qcrypto
LIBS += crypto
LIBS += sdrvproperty
LIBS += sdrv-shm

#####AUTO-GENERATED by packaging script... do not checkin#####
   INSTALL_ROOT_nto = $(PROJECT_ROOT)/../../../../install
   USE_INSTALL_ROOT=1
##############################################################

include $(MKFILES_ROOT)/qmacros.mk

include $(MKFILES_ROOT)/qtargets.mk
